### PR TITLE
Create CNAME file

### PR DESCRIPTION
**Pull request by sishida**
Hi, team,
I'm adding this CNAME file to the repo based on the one I saw in John's repo here: https://github.com/jduimovich/microclimate.dev.github.io/blob/master/CNAME

### CODE REVIEW

**Comment by sishida** [comment]
Possible concerns (shared by Tim Etchells in the landing-pages issue):
- As Martin mentioned, we don't want to break the existing `microclimate-dev2ops.github.io` links.
- This change might 'override' John D's existing CNAME, so we might need to ask him to take his fork down.

**Comment by tetchel** [comment]
we _want_ it to override john's repo. the concern is that this might not.

**Comment by jduimovich** [comment]
This will break all the microclimate-dev2ops.github.io links so the master cannot have a CNAME.

The way I have it setup is 
1) I have a fork of microclimate-dev2ops.github.io  at https://github.com/jduimovich/microclimate-dev2ops.github.io  has openmicroclimate.io as the CNAME
2) I also have separate remote in the above repo which points to  https://github.com/jduimovich/microclimate.dev.github.io which has microclimate.dev as the CNAME

When I update my https://github.com/jduimovich/microclimate-dev2ops.github.io  I rebase and keep the CNAME (openmicroclimate.io) in my fork which I push to master
I also rebase a branch in https://github.com/jduimovich/microclimate-dev2ops.github.io and keep its CNAME as microclimate.dev which I then push to the remote at https://github.com/jduimovich/microclimate.dev.github.io

It's  bit manual at the moment.

If you want to move this into microclimate itself, you will need to mirror this setup.
1) an openmicroclimate.io repo
2) a microclimate.dev repo
a remote in microclimate-dev2ops.github.io for two branches which you keep rebased on master with only CNAME as an addition to each for their respective names.

**Comment by sishida** [comment]
Thanks for letting us know! Because the CNAME in master will break links, I will close this pull request and add further thoughts in the issue: https://github.ibm.com/dev-ex/landing-pages/issues/1043.

**Pull request merged**
